# Generated by Django 4.2.7 on 2023-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_usuario_alter_pais_nombre_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
