# Generated by Django 4.2.7 on 2023-12-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_videos_alter_comentario_post_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='autor',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.FileField(blank=True, default='avatares/avatar_predeterminado.webp', null=True, upload_to='avatares/'),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
