# Generated by Django 4.2.7 on 2023-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='autor',
            field=models.CharField(default='', help_text='ingrese su nombre de usuario', max_length=20),
            preserve_default=False,
        ),
    ]
