# Generated by Django 4.2.7 on 2023-12-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_comentarios_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='autor',
            field=models.CharField(help_text='(ingrese su nombre de usuario)', max_length=20),
        ),
    ]
