# Generated by Django 4.2.7 on 2023-12-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_comentarios_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
